package packages.baby.frames;

import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.text.BadLocationException;

/**
 *
 * @author liaminakigillamac
 */

public class Ide extends javax.swing.JFrame {
//    private String codeContent;
    
    
    
    public Ide() {
        setTitle("Baby");
        initComponents();
        setupKeyboardShortcuts();
        WindowClosingHandler();
        Image img = new ImageIcon(this.getClass().getResource("/icons/Logo.png")).getImage();
        this.setIconImage(img);
    }
    
    
    private void WindowClosingHandler() {
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                handleWindowClosing();
                
            }
        });
        
    }

    public void handleWindowClosing() {
        
        if (editor != null && editor.hasUnsavedChanges()) {
            int choice = JOptionPane.showConfirmDialog(Ide.this,
                "You have unsaved changes. Do you want to exit without saving?",
                "Confirm Exit",
                JOptionPane.YES_NO_OPTION
            );

            if (choice == JOptionPane.NO_OPTION) {
                return;
            }
        }
        
        dispose();

    }
    
    //checks if the HomeScreen window is open
    public boolean isHomeScreenOpen() {
        Frame[] frames = Frame.getFrames();
        for (Frame frame : frames) {
            if (frame instanceof HomeScreen) {
                return true;
            }
        }
        return false;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idePnl = new javax.swing.JPanel();
        sidebarPnl = new javax.swing.JPanel();
        Home = new packages.baby.components.SidebarBtn();
        Save = new packages.baby.components.SidebarBtn();
        SaveAs = new packages.baby.components.SidebarBtn();
        Open = new packages.baby.components.SidebarBtn();
        TempUndo = new packages.baby.components.SidebarBtn();
        TempRedo = new packages.baby.components.SidebarBtn();
        editor = new packages.baby.components.CodeEditor();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        newWindow = new javax.swing.JMenuItem();
        newTab = new javax.swing.JMenuItem();
        openFile = new javax.swing.JMenuItem();
        closeFile = new javax.swing.JMenuItem();
        save = new javax.swing.JMenuItem();
        saveAs = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        undo = new javax.swing.JMenuItem();
        redo = new javax.swing.JMenuItem();
        cut = new javax.swing.JMenuItem();
        copy = new javax.swing.JMenuItem();
        paste = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        runCode = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Baby");
        setBackground(new java.awt.Color(31, 31, 31));
        setPreferredSize(new java.awt.Dimension(1024, 768));

        idePnl.setBackground(new java.awt.Color(51, 51, 51));
        idePnl.setForeground(new java.awt.Color(31, 31, 31));
        idePnl.setToolTipText("");

        sidebarPnl.setBackground(new java.awt.Color(31, 31, 31));

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home.png"))); // NOI18N
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        SaveAs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/saveAs.png"))); // NOI18N
        SaveAs.setToolTipText("");
        SaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveAsActionPerformed(evt);
            }
        });

        Open.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/openFile.png"))); // NOI18N
        Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenActionPerformed(evt);
            }
        });

        TempUndo.setForeground(new java.awt.Color(255, 255, 255));
        TempUndo.setText("Undo");
        TempUndo.setToolTipText("");
        TempUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TempUndoActionPerformed(evt);
            }
        });

        TempRedo.setForeground(new java.awt.Color(255, 255, 255));
        TempRedo.setText("Redo");
        TempRedo.setToolTipText("");
        TempRedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TempRedoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidebarPnlLayout = new javax.swing.GroupLayout(sidebarPnl);
        sidebarPnl.setLayout(sidebarPnlLayout);
        sidebarPnlLayout.setHorizontalGroup(
            sidebarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPnlLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(sidebarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Open, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaveAs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TempUndo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TempRedo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        sidebarPnlLayout.setVerticalGroup(
            sidebarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPnlLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Open, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SaveAs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TempUndo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TempRedo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout idePnlLayout = new javax.swing.GroupLayout(idePnl);
        idePnl.setLayout(idePnlLayout);
        idePnlLayout.setHorizontalGroup(
            idePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idePnlLayout.createSequentialGroup()
                .addComponent(sidebarPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(editor, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE)
                .addGap(38, 38, 38))
        );
        idePnlLayout.setVerticalGroup(
            idePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebarPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(idePnlLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(editor, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addGap(342, 342, 342))
        );

        getContentPane().add(idePnl, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        newWindow.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_N,Toolkit.getDefaultToolkit().getMenuShortcutKeyMask()));
        newWindow.setText("New Window");
        newWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newWindowActionPerformed(evt);
            }
        });
        jMenu1.add(newWindow);

        newTab.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        newTab.setText("New Tab");
        newTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTabActionPerformed(evt);
            }
        });
        jMenu1.add(newTab);

        openFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        openFile.setText("Open File");
        openFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileActionPerformed(evt);
            }
        });
        jMenu1.add(openFile);

        closeFile.setText("Close File");
        closeFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeFileActionPerformed(evt);
            }
        });
        jMenu1.add(closeFile);

        save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jMenu1.add(save);

        saveAs.setText("Save As");
        saveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsActionPerformed(evt);
            }
        });
        jMenu1.add(saveAs);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        undo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        undo.setText("Undo");
        undo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoActionPerformed(evt);
            }
        });
        jMenu2.add(undo);

        redo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        redo.setText("Redo");
        redo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redoActionPerformed(evt);
            }
        });
        jMenu2.add(redo);

        cut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        cut.setText("Cut");
        cut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutActionPerformed(evt);
            }
        });
        jMenu2.add(cut);

        copy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        copy.setText("Copy");
        copy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyActionPerformed(evt);
            }
        });
        jMenu2.add(copy);

        paste.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        paste.setText("Paste");
        paste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasteActionPerformed(evt);
            }
        });
        jMenu2.add(paste);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Run");

        runCode.setText("Run Code");
        jMenu3.add(runCode);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        
        if (!isHomeScreenOpen()) {
            HomeScreen home = new HomeScreen();
            home.setVisible(true);
        }
        
        else {
            System.out.println("Failed");
        }
//        //opens the home screen
//        HomeScreen home = new HomeScreen ();
//        home.show(); //display homeScreen here
//        
//        dispose(); //close the current frame after opening homeScreen
        
    }//GEN-LAST:event_HomeActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        editor.save();
    }//GEN-LAST:event_SaveActionPerformed

    private void SaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveAsActionPerformed
        editor.saveAs();
    }//GEN-LAST:event_SaveAsActionPerformed

    private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
        if (editor.hasUnsavedChanges()){
            int choice = JOptionPane.showConfirmDialog(
            Ide.this,
            "You have unsaved changes. Do you want to open another file without saving?",
            "Confirm Exit",
            JOptionPane.YES_NO_OPTION
            );
            
            if (choice == JOptionPane.NO_OPTION) {
                return;
            }
        }
        
        editor.open();
    }//GEN-LAST:event_OpenActionPerformed

    private void newWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newWindowActionPerformed
        Ide ide = new Ide();
        ide.setVisible(true);
    }//GEN-LAST:event_newWindowActionPerformed

    private void openFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileActionPerformed
        if (editor.hasUnsavedChanges()){
            int choice = JOptionPane.showConfirmDialog(
            Ide.this,
            "You have unsaved changes. Do you want to open another file without saving?",
            "Confirm Exit",
            JOptionPane.YES_NO_OPTION
            );
            
            if (choice == JOptionPane.NO_OPTION) {
                return;
            }
        }
        
        editor.open();
    }//GEN-LAST:event_openFileActionPerformed

    private void undoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoActionPerformed
        editor.undo();
    }//GEN-LAST:event_undoActionPerformed

    private void TempUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TempUndoActionPerformed
        editor.undo();
    }//GEN-LAST:event_TempUndoActionPerformed

    private void TempRedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TempRedoActionPerformed
        editor.redo();
    }//GEN-LAST:event_TempRedoActionPerformed

    private void redoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redoActionPerformed
        editor.redo();
    }//GEN-LAST:event_redoActionPerformed

    private void closeFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeFileActionPerformed
        if (editor.hasUnsavedChanges()){
            int choice = JOptionPane.showConfirmDialog(
            Ide.this,
            "You have unsaved changes. Do you want to open another file without saving?",
            "Confirm Exit",
            JOptionPane.YES_NO_OPTION
            );
            
            if (choice == JOptionPane.NO_OPTION) {
                return;
            }
        }
        
        editor.close();
    }//GEN-LAST:event_closeFileActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        editor.save();
    }//GEN-LAST:event_saveActionPerformed


    private void saveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsActionPerformed
        editor.saveAs();
    }//GEN-LAST:event_saveAsActionPerformed


    private void cutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutActionPerformed
        try {
            editor.cut();
        } catch (BadLocationException ex) {
            Logger.getLogger(Ide.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cutActionPerformed

    private void copyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyActionPerformed
        System.out.println("Mid");
        try {
            editor.copy();
        } catch (BadLocationException ex) {
            Logger.getLogger(Ide.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_copyActionPerformed

    private void pasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasteActionPerformed
        editor.paste();

    }//GEN-LAST:event_pasteActionPerformed

    private void newTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newTabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newTabActionPerformed

    

    public void openAction(java.awt.event.ActionEvent evt) {
        OpenActionPerformed(evt);
    }
    
    private void setupKeyboardShortcuts() {
        int menuShortcutKey = Toolkit.getDefaultToolkit().getMenuShortcutKeyMaskEx();
          
        // Set up the Save keyboard shortcut (Ctrl + S or Cmd + S)
        setupKeyboardShortcut("Save", KeyEvent.VK_S, menuShortcutKey);

        // Set up the Save As keyboard shortcut (Shift + Ctrl + S or Shift + Cmd + S)
        setupKeyboardShortcut("Save As", KeyEvent.VK_S, KeyEvent.SHIFT_DOWN_MASK | menuShortcutKey);
        
        // Set up the Save As keyboard shortcut (Ctrl + S or Cmd + Z)
        setupKeyboardShortcut("Undo", KeyEvent.VK_Z, menuShortcutKey);
        
        // Set up the Save As keyboard shortcut (Shift + Ctrl + Z or Shift + Cmd + Z)
        setupKeyboardShortcut("Redo", KeyEvent.VK_Z, KeyEvent.SHIFT_DOWN_MASK | menuShortcutKey);
        
        // Set up the New Window keyboard shortcut (Ctrl + N or Cmd + N)
        setupKeyboardShortcut("New Window", KeyEvent.VK_N, menuShortcutKey);
        
        // Set up the Open File keyboard shortcut (Ctrl + O) or Cmd + O)
        setupKeyboardShortcut("Open File", KeyEvent.VK_O, menuShortcutKey);
        
        // Set up the Open File keyboard shortcut (Ctrl + C) or Cmd + C)
        setupKeyboardShortcut("Copy", KeyEvent.VK_C, menuShortcutKey);
    }

    private void setupKeyboardShortcut(String actionName, int keyCode, int modifier) {
        
        Action action = new AbstractAction(actionName) {
            @Override
            public void actionPerformed(ActionEvent e) {
                handleAction(actionName);
            }
        };

        action.putValue(Action.MNEMONIC_KEY, keyCode);

        KeyStroke keyStroke = KeyStroke.getKeyStroke(keyCode, modifier);
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(keyStroke, actionName);
        getRootPane().getActionMap().put(actionName, action);
    }
    
    private void handleAction(String actionName) {
        ActionEvent event = new ActionEvent(this, ActionEvent.ACTION_PERFORMED, actionName);

        switch (actionName) {
            case "Save" -> SaveActionPerformed(event);
            case "Save As" -> SaveAsActionPerformed(event);
            case "Undo" -> TempUndoActionPerformed(event);
            case "Redo" -> TempRedoActionPerformed(event);
            case "New Window" -> newWindowActionPerformed(event);
            case "Open File" -> OpenActionPerformed(event);
            case "Copy" -> copyActionPerformed(event);
        }
    }
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private packages.baby.components.SidebarBtn Home;
    private packages.baby.components.SidebarBtn Open;
    private packages.baby.components.SidebarBtn Save;
    private packages.baby.components.SidebarBtn SaveAs;
    private packages.baby.components.SidebarBtn TempRedo;
    private packages.baby.components.SidebarBtn TempUndo;
    private javax.swing.JMenuItem closeFile;
    private javax.swing.JMenuItem copy;
    private javax.swing.JMenuItem cut;
    private packages.baby.components.CodeEditor editor;
    private javax.swing.JPanel idePnl;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem newTab;
    private javax.swing.JMenuItem newWindow;
    private javax.swing.JMenuItem openFile;
    private javax.swing.JMenuItem paste;
    private javax.swing.JMenuItem redo;
    private javax.swing.JMenuItem runCode;
    private javax.swing.JMenuItem save;
    private javax.swing.JMenuItem saveAs;
    private javax.swing.JPanel sidebarPnl;
    private javax.swing.JMenuItem undo;
    // End of variables declaration//GEN-END:variables
}
